sudo: required
services:
  - docker

before_install:
  - docker build -t rszczesiak/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rszczesiak/react-test npm test -- --coverage

after_success:
  - docker build -t rszczesiak/multi-client ./client
  - docker build -t rszczesiak/multi-nginx ./nginx
  - docker build -t rszczesiak/multi-server ./server
  - docker build -t rszczesiak/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push rszczesiak/multi-client
  - docker push rszczesiak/multi-nginx
  - docker push rszczesiak/multi-server
  - docker push rszczesiak/multi-worker
  